server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/rbenitec/proyecto_coches
          search-paths: config-data
  application:
    name: config-server

